// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNXHk9rWbu3Ej3ryVHsXP2aBXDChLUjBQ',
    appId: '1:1040105162322:web:18b815b3f114a1e2a5418b',
    messagingSenderId: '1040105162322',
    projectId: 'jsalayo-portfolio',
    authDomain: 'jsalayo-portfolio.firebaseapp.com',
    storageBucket: 'jsalayo-portfolio.appspot.com',
    measurementId: 'G-Q6F0NF6QR6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHsT16EjjgmMKOe0Q1QT7YpDbpKWtyekw',
    appId: '1:1040105162322:android:50920a8cb714095ea5418b',
    messagingSenderId: '1040105162322',
    projectId: 'jsalayo-portfolio',
    storageBucket: 'jsalayo-portfolio.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0DmuDqjZVA7lZd0NAUSRV760YAur4RMU',
    appId: '1:1040105162322:ios:6b17e742b3c1d8a1a5418b',
    messagingSenderId: '1040105162322',
    projectId: 'jsalayo-portfolio',
    storageBucket: 'jsalayo-portfolio.appspot.com',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0DmuDqjZVA7lZd0NAUSRV760YAur4RMU',
    appId: '1:1040105162322:ios:be3a8b33e54c4066a5418b',
    messagingSenderId: '1040105162322',
    projectId: 'jsalayo-portfolio',
    storageBucket: 'jsalayo-portfolio.appspot.com',
    iosBundleId: 'com.example.portfolio.RunnerTests',
  );
}
